# Generated by Django 5.1.15 on 2026-08-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active_tasks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='workload_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
