# Generated by Django 5.1.15 on 2026-08-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_active_tasks_employee_workload_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='availability_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('On Leave', 'On Leave')], default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='available_hours',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
